"""Explicit interruption, exception, and timer microprogram membership."""

from .encoding import TEST_NAMES

GROUP = 'interrupt'
CASE_NAMES = (
    'ar_itc_advances_in_guest_loop',
    'async_timer_interrupt_enters_ivt',
    'async_timer_interrupt_never_resumes_mlx_slot2',
    'async_timer_interrupt_preserves_bank1_grs',
    'async_timer_interrupt_records_boundary_ri',
    'break_preserves_ifa_and_records_iim_isr',
    'cloop_zero_st1_timer_interrupts_batched_loop',
    'counted_self_loop_fault_has_slot1_ri',
    'cover_saves_interrupted_cfm_to_ifs',
    'exception_break',
    'exception_break_f',
    'exception_break_x',
    'exception_clears_ifs_keeps_cfm',
    'exception_entry_initializes_psr',
    'exception_illegal',
    'exception_illegal_enters_general_vector',
    'exception_records_slot_ri',
    'exception_reserved_template',
    'exception_syscall_break',
    'exception_unaligned',
    'exception_unaligned_sets_ifa_isr',
    'exception_unaligned_slot1_uses_psr_ri',
    'future_itm_rearm_preserves_pended_timer_irr',
    'iipa_preserved_for_rfi_to_fault',
    'iipa_reports_current_bundle_after_prior_slot_success',
    'iipa_reports_previous_successful_bundle_for_slot0_fault',
    'invalid_itv_vector_is_ignored',
    'masked_itv_discards_due_timer',
    'masking_itv_preserves_pended_timer_irr',
    'mov_from_psr_does_not_copy_execution_slot_to_rfi',
    'mov_pkr_does_not_alias_interruption_crs',
    'mov_to_irr_illegal',
    'mov_to_ivr_illegal',
    'mov_to_read_only_cr_predicate_false',
    'nested_exception_keeps_handler_interruption_state',
    'nested_exception_keeps_handler_return_state',
    'past_itm_does_not_fire',
    'past_rearmed_itm_does_not_interrupt',
    'rfi_ignores_iip_low_bits',
    'rfi_restores_interrupted_bsp_after_cover',
    'rfi_resumes_at_ipsr_ri_slot',
    'rfi_retries_interrupted_current_frame_fill',
    'rfi_target_rse_fill_fault_uses_restored_psr',
    'rfi_montecito_native_ia32_disabled_fault',
    'rfi_montecito_uncollected_transition_preserves_target',
    'rse_large_frame_timer_rfi_preserves_high_caller_local',
    'repeated_timer_rfi_preserves_word_rmw',
    'timer_cover_rfi_preserves_large_frame_halfword_rmw',
    'timer_interrupt_preserves_banked_word_rmw',
    'sapic_extint_masks_external_until_eoi',
    'sapic_same_class_higher_vector_preempts',
    'timer_interrupt_exits_chained_loop_after_virtual_deadline',
    'tpr_mmi_masks_timer_until_cleared',
    'tpr_preserves_mmi_and_mic',
    'unimplemented_physical_instruction_traps',
)

CASES = {name: TEST_NAMES[name] for name in CASE_NAMES}
